_sandboxbwrap.py: Catch ENOTCONN when umounting
When umounting devices such as /dev/null, /dev/full,...in some
systems (seen in aarch64) the device is not ready or not there when
trying to umount, this raises the following error:

```
    An unhandled exception occured:

    Traceback (most recent call last):
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/_fuse/mount.py", line 148, in mounted
        yield
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_mount.py", line 84, in mounted
        yield
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_mount.py", line 142, in mounted
        yield
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_sandboxbwrap.py", line 207, in run
        self.try_remove_device(device_path)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_sandboxbwrap.py", line 386, in try_remove_device
        os.unlink(device_path)
    OSError: [Errno 107] Transport endpoint is not connected: '/home/ubuntu/.cache/buildstream/build/gnu-toolchain-stage2-fhs-dirs-k5ih53a6/scratch/_/mount/dev/full'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/_scheduler/job.py", line 340, in _child_action
        result = self._action_cb(element)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/_scheduler/buildqueue.py", line 33, in process
        element._assemble()
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/element.py", line 1439, in _assemble
        self.stage(sandbox)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/buildelement.py", line 170, in stage
        dep.integrate(sandbox)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/element.py", line 782, in integrate
        exitcode = sandbox.run(['sh', '-e', '-c', cmd], 0, env=environment, cwd='/')
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_sandboxbwrap.py", line 242, in run
        pass
      File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
        raise exc_details[1]
      File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
        if cb(*exc_details):
      File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
        return cm_exit(cm, *exc_details)
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_mount.py", line 142, in mounted
        yield
      File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
        raise exc_details[1]
      File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
        if cb(*exc_details):
      File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
        return cm_exit(cm, *exc_details)
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/sandbox/_mount.py", line 84, in mounted
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/_fuse/mount.py", line 150, in mounted
        self.unmount()
      File "/mnt/buildstream-workspace/projects/buildstream/buildstream/_fuse/mount.py", line 128, in unmount
        .format(type(self).__name__, self.__process.exitcode))
    buildstream._fuse.mount.FuseMountError: SafeHardlinks reported exit code -11 when unmounting
```

Causing also a coredump in libffi.

To avoid this issue, the `[Errno 107] Transport endpoint is not connected`
exception is catched trying to wait for these devices to be available
and umounted.

Issue #161